seleniumhub:
  image: selenium/hub:latest
  ports:
    - 4444:4444

# firefoxnode:
#   image: selenium/node-firefox
#   expose:
#     - 5900
#   links:
#     - seleniumhub:hub

chromenode:
  image: selenium/node-chrome:latest
  ports:
    - 5900
  links:
    - seleniumhub:hub



